### ISSUE TITLE
version 1.8.5 can not run

### ISSUE THREAD

**Issue by hola5156** [NevermindNilas/TheAnimeScripter#32]
![20240619191801](https://github.com/NevermindNilas/TheAnimeScripter/assets/151821949/0663312b-fcd8-4e96-95b5-66d5997798d6)

**Comment by NevermindNilas** [comment]
Hi,

I will take a look and release a hotfix today

**Comment by przemoc** [comment]
Error in text form for better searchability:

```
Traceback (most recent call last):
  File "main.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\ffmpegSettings.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "decord\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "decord\_ffi\runtime_ctypes.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "decord\_ffi\base.py", line 47, in <module>
  File "decord\_ffi\base.py", line 37, in _load_lib
  File "decord\_ffi\libinfo.py", line 80, in find_lib_path
RuntimeError: Cannot find the files.
List of candidates:
C:\Tools\TAS185\_internal\decord\libdecord.dll
C:\Tools\TAS185\build\libdecord.dll
C:\Tools\TAS185\build\Release\libdecord.dll
C:\Tools\TAS185\lib\libdecord.dll
C:\Tools\libdecord.dll
C:\Tools\TAS185\_internal\decord\decord.dll
C:\Tools\TAS185\build\decord.dll
C:\Tools\TAS185\build\Release\decord.dll
C:\Tools\TAS185\lib\decord.dll
C:\Tools\decord.dll
[8120] Failed to execute script 'main' due to unhandled exception!
```

**Comment by NevermindNilas** [comment]
I guess the new library I used for faster decoding named Decord doesn't have some hooks for some of the dlls it needs and pyinstaller can not recognize their existence. I hope that --colect-all will fix the issue but no pinky promises.

**Comment by NevermindNilas** [comment]
![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/128264457/34b93f8d-fccb-4cb3-b7e8-47b1d4b7eaef)

Managed to fix the build issues with https://github.com/NevermindNilas/TheAnimeScripter/commit/3628f0185b8c61e13120683e091b39fc5ad560a9

Thanks for the issue, a hotfix release will be coming in ~30 min.
