### ISSUE TITLE
TAS v1.9.7 span+rife will result in flicker interpolated frames

### ISSUE THREAD

**Issue by GoldJohnKing** [NevermindNilas/TheAnimeScripter#48]
Hi, I updated to v1.9.7 and use span to super resolution my video.

The output frames do not look right.

![屏幕截图(279)](https://github.com/user-attachments/assets/261c698d-933e-4fc1-b20c-cb6c20e6ac01)

Please notice the colored dots over any plane area and colored lines around object borders.

As a comparison, a normal frame should be.

![屏幕截图(280)](https://github.com/user-attachments/assets/d6aac1ea-7e2b-42db-9c1b-1017f2b8d0d3)

My command:

```sh
..\%tas_folder%\main.exe --input %input_video% --output %output_video% ^
--upscale --upscale_factor %upscale_factor% --upscale_method span ^
--scenechange --scenechange_method maxxvit-tensorrt ^
--custom_encoder="-c:a copy -c:v hevc_nvenc -preset p7 -tune hq -profile:v main -pix_fmt yuv420p -tier high -rc constqp -qp 15"
```

v1.9.4 does not have the issue.

**Comment by NevermindNilas** [comment]
Hi, this is probably a clamping issue, values may be out of 0-255 range.

I will try to see if I can fix it for 1.9.8

**Comment by GoldJohnKing** [comment]
Hi, I have tried nightly build of TAS, it outputs an error when using span together with rife.

```
============== Processing Outputs ==============
Upscaling to 5040x2160
Interpolating from 60.000fps to 120.000fps
UHD and fp16 for rife are not compatible due to flickering issues, defaulting to fp32
Something went wrong: Input type (float) and bias type (struct c10::Half) should be the same
Traceback (most recent call last):
  File "main.py", line 227, in start
  File "src\initializeModels.py", line 332, in initializeModels
    interpolate_process = RifeTensorRT(
                          ^^^^^^^^^^^^^
  File "src\unifiedInterpolate.py", line 257, in __init__
    self.handleModel()
  File "src\unifiedInterpolate.py", line 375, in handleModel
    torch.onnx.export(
  File "torch\onnx\__init__.py", line 377, in export
    export(
  File "torch\onnx\utils.py", line 502, in export
    _export(
  File "torch\onnx\utils.py", line 1564, in _export
    graph, params_dict, torch_out = _model_to_graph(
                                    ^^^^^^^^^^^^^^^^
  File "torch\onnx\utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\onnx\utils.py", line 997, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\onnx\utils.py", line 904, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\jit\_trace.py", line 1500, in _get_trace_graph
    outs = ONNXTracedModule(
           ^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\jit\_trace.py", line 139, in forward
    graph, out = torch._C._create_graph_by_tracing(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\jit\_trace.py", line 130, in wrapper
    outs.append(self.inner(*trace_inputs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1726, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\rifearches\Rife422_v2.py", line 152, in forward
    fs2 = self.encode(imgs2)
          ^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1726, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\rifearches\Rife422_v2.py", line 47, in forward
    x0 = self.cnn0(x)
         ^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1726, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same
```

I set `--half False` but still no luck.

My command is:

```
..\%tas_folder%\main.exe --half False --buffer_limit 100 ^
--input %input_video% --output %output_video% ^
--upscale --upscale_factor %upscale_factor% --upscale_method span ^
--scenechange --scenechange_method maxxvit-tensorrt ^
--interpolate --interpolate_factor %interpolate_factor% --interpolate_method rife4.22-tensorrt ^
--custom_encoder="-c:a copy -c:v hevc_nvenc -preset p7 -tune hq -profile:v main -pix_fmt yuv420p -tier high -rc constqp -qp 15"
```

Here is the full log.

[log.txt](https://github.com/user-attachments/files/16882267/log.txt)

**Comment by NevermindNilas** [comment]
Yeah, the nightly you used may have been a previous one without some bugfixes.

Please try again with the latest build and lmk if it does work or not.

**Comment by GoldJohnKing** [comment]
Hi, I have tested [TAS_Nightly_2024_09_05](https://github.com/NevermindNilas/TAS-Nightly/releases/tag/TAS_2024_09_05), still no luck.

The log says onnx is not installed.

[log.txt](https://github.com/user-attachments/files/16897962/log.txt)

**Comment by NevermindNilas** [comment]
Well that's interesting since it does seem to be present in TAS _internal folder.

Can u open an issue so to keep things more tidy.

**Comment by GoldJohnKing** [comment]
> Well that's interesting since it does seem to be present in TAS _internal folder.
> 
> Can u open an issue so to keep things more tidy.

Hi, I just tested latest nightly build, this issue is fixed. 😄
